### PR TITLE
Added the required Tara's Blog to Readme file

### PR DESCRIPTION
**Pull request by Shaikh-Ubaid**

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Hi @Shaikh-Ubaid ,
Thanks for the PR for a blog post can you just add the link, and also the gifs , can you check how we can embed them in .md file as they are available on youtube.

**Comment by Shaikh-Ubaid** [comment]
I tried to embed youtube videos directly, but it seems that you cannot embed videos in markdown. So, I created gifs of those videos and then embedded them. As much as I have understood, you want only the link and the gifs to be present in the readme file and not the whole blog. Please let me know if I am correct.
Also one way to add youtube videos is to embed the

**Comment by santoshyadav198613** [comment]
> I tried to embed youtube videos directly, but it seems that you cannot embed videos in markdown. So, I created gifs of those videos and then embedded them. As much as I have understood, you want only the link and the gifs to be present in the readme file and not the whole blog. Please let me know if I am correct.
> Also, one way to add youtube videos is to embed a clickable image of video which directs the user to the video on youtube. Please let me know if you want this instead of gifs.
Yes, we just need the link, as we don't want to copy entire content.

**Comment by santoshyadav198613** [comment]
LGTM Thanks for the contribution.

**Pull request merged**
