### PR TITLE
Changed app structure to ngx-deploy-starter

### PR DESCRIPTION
**Pull request by iamsurajdc**
Issue #50
Changed app structure to ngx-deploy-starter

### CODE REVIEW

**Comment by santoshyadav198613** [comment]
Thank for PR, will get it reviewed.

**Comment by iamsurajdc** [comment]
Sure Sir! @santoshyadav198613

**Comment by JohannesHoppe** [comment]
This is very cool! 👍

**Comment by santoshyadav198613** [comment]
Hi @iamsurajdc ,
can you resolve the merge conflict will get it merged.

**Comment by JohannesHoppe** [comment]
However, this would only be a start. Filenames and content are still very different.

A unified file structure would help us to share patches much more easier. (I do this with cherry picks between ngx-deploy-starter and angular-cli-ghpages)

**Comment by iamsurajdc** [comment]
> Hi @iamsurajdc ,
> can you resolve the merge conflict will get it merged.

Hi @santoshyadav198613  Sir, I request you to check now.

**Comment by santoshyadav198613** [comment]
> > Hi @iamsurajdc ,
> > can you resolve the merge conflict will get it merged.
> 
> Hi @santoshyadav198613 Sir, I request you to check now.

Still the same you can use 

1. git reset --soft HEAD~1
2. git commit -m 'Changed app structure to ngx-deploy-starter'
3. git fetch upstream master
4. git rebase upstream/master
5. git push -f

Let me know if it works.

**Comment by iamsurajdc** [comment]
> Still the same you can use
> 
> 1. git reset --soft HEAD~1
> 2. git commit -m 'Changed app structure to ngx-deploy-starter'
> 3. git fetch upstream master
> 4. git rebase upstream/master
> 5. git push -f
> 
> Let me know if it works.

I've executed that commands. You can check now. Also, I apologize for the delay.

**Comment by santoshyadav198613** [comment]
Hi Suraj, 
rn the below command first and than run the given commands
git remote add upstream https://github.com/ngx-builders/netlify-builder.git

**Pull request merged**
